# Generated by Django 5.2.6 on 2025-09-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dailyfollowup_date_alter_dailyfollowup_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_month', to='api.paymentmonth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_month', to='api.paymentmonth'),
        ),
    ]
