# Generated by Django 5.2.6 on 2025-09-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_quiz_date_quiz_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
