import type { Metadata } from "next";
import "./globals.css";
import { Tajawal } from "next/font/google";
import Navbar from "../components/navbar";
import { Toaster } from "sonner";
import Providers from "./providers";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
});


export default function RootLayout({
  children,
  profilemodal
}: {
  children: React.ReactNode,
  profilemodal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${tajawal.className}`}
      >
        <div className="flex w-[100%] flex-col min-h-screen">
          <Providers>
            <Navbar />
            <main className="flex-1 bg-gray-100 min-h-[90vh] pt-30">
              {children}
              {profilemodal}
            </main>
            <Toaster
              position="top-center"
              richColors
              dir="rtl"
            />
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
